package com.zzptc.sky.netnews.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NEWS_CHANNEL_TABLE".
 */
@Entity
public class NewsChannelTable {

    @Id
    @NotNull
    private String newsChannelName;

    @NotNull
    private String newsChannelId;

    @NotNull
    private String newsChannelType;
    private boolean newsChannelSelect;
    private int newsChannelIndex;
    private boolean newsChannelFixed;

    @Generated(hash = 518806505)
    public NewsChannelTable() {
    }

    public NewsChannelTable(String newsChannelName) {
        this.newsChannelName = newsChannelName;
    }

    @Generated(hash = 90674627)
    public NewsChannelTable(@NotNull String newsChannelName, @NotNull String newsChannelId, @NotNull String newsChannelType, boolean newsChannelSelect, int newsChannelIndex,
            boolean newsChannelFixed) {
        this.newsChannelName = newsChannelName;
        this.newsChannelId = newsChannelId;
        this.newsChannelType = newsChannelType;
        this.newsChannelSelect = newsChannelSelect;
        this.newsChannelIndex = newsChannelIndex;
        this.newsChannelFixed = newsChannelFixed;
    }

    @NotNull
    public String getNewsChannelName() {
        return newsChannelName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNewsChannelName(@NotNull String newsChannelName) {
        this.newsChannelName = newsChannelName;
    }

    @NotNull
    public String getNewsChannelId() {
        return newsChannelId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNewsChannelId(@NotNull String newsChannelId) {
        this.newsChannelId = newsChannelId;
    }

    @NotNull
    public String getNewsChannelType() {
        return newsChannelType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNewsChannelType(@NotNull String newsChannelType) {
        this.newsChannelType = newsChannelType;
    }

    public boolean getNewsChannelSelect() {
        return newsChannelSelect;
    }

    public void setNewsChannelSelect(boolean newsChannelSelect) {
        this.newsChannelSelect = newsChannelSelect;
    }

    public int getNewsChannelIndex() {
        return newsChannelIndex;
    }

    public void setNewsChannelIndex(int newsChannelIndex) {
        this.newsChannelIndex = newsChannelIndex;
    }

    public boolean getNewsChannelFixed() {
        return newsChannelFixed;
    }

    public void setNewsChannelFixed(boolean newsChannelFixed) {
        this.newsChannelFixed = newsChannelFixed;
    }

}
